export const divisions = [
  { value: 'dhaka', label: 'ঢাকা' },
  { value: 'chittagong', label: 'চট্টগ্রাম' },
  { value: 'rajshahi', label: 'রাজশাহী' },
  { value: 'khulna', label: 'খুলনা' },
  { value: 'barisal', label: 'বরিশাল' },
  { value: 'sylhet', label: 'সিলেট' },
  { value: 'rangpur', label: 'রংপুর' },
  { value: 'mymensingh', label: 'ময়মনসিংহ' },
];

export const BD_LOCATIONS = [
  { division: 'Dhaka', divisionBn: 'ঢাকা', districts: ['Dhaka', 'Faridpur', 'Gazipur', 'Gopalganj', 'Kishoreganj', 'Madaripur', 'Manikganj', 'Munshiganj', 'Narayanganj', 'Narsingdi', 'Rajbari', 'Shariatpur', 'Tangail'] },
  { division: 'Chittagong', divisionBn: 'চট্টগ্রাম', districts: ['Bandarban', 'Brahmanbaria', 'Chandpur', 'Chittagong', 'Comilla', 'Cox\'s Bazar', 'Feni', 'Khagrachhari', 'Lakshmipur', 'Noakhali', 'Rangamati'] },
  { division: 'Rajshahi', divisionBn: 'রাজশাহী', districts: ['Bogra', 'Joypurhat', 'Naogaon', 'Natore', 'Chapainawabganj', 'Pabna', 'Rajshahi', 'Sirajganj'] },
  { division: 'Khulna', divisionBn: 'খুলনা', districts: ['Bagerhat', 'Chuadanga', 'Jessore', 'Jhenaidah', 'Khulna', 'Kushtia', 'Magura', 'Meherpur', 'Narail', 'Satkhira'] },
  { division: 'Barisal', divisionBn: 'বরিশাল', districts: ['Barguna', 'Barisal', 'Bhola', 'Jhalokati', 'Patuakhali', 'Pirojpur'] },
  { division: 'Sylhet', divisionBn: 'সিলেট', districts: ['Habiganj', 'Moulvibazar', 'Sunamganj', 'Sylhet'] },
  { division: 'Rangpur', divisionBn: 'রংপুর', districts: ['Dinajpur', 'Gaibandha', 'Kurigram', 'Lalmonirhat', 'Nilphamari', 'Panchagarh', 'Rangpur', 'Thakurgaon'] },
  { division: 'Mymensingh', divisionBn: 'ময়মনসিংহ', districts: ['Jamalpur', 'Mymensingh', 'Netrokona', 'Sherpur'] },
];

export const districts: Record<string, { value: string; label: string }[]> = {
  dhaka: [
    { value: 'dhaka', label: 'ঢাকা' },
    { value: 'faridpur', label: 'ফরিদপুর' },
    { value: 'gazipur', label: 'গাজীপুর' },
    { value: 'gopalganj', label: 'গোপালগঞ্জ' },
    { value: 'kishoreganj', label: 'কিশোরগঞ্জ' },
    { value: 'madaripur', label: 'মাদারীপুর' },
    { value: 'manikganj', label: 'মানিকগঞ্জ' },
    { value: 'munshiganj', label: 'মুন্সিগঞ্জ' },
    { value: 'narayanganj', label: 'নারায়ণগঞ্জ' },
    { value: 'narsingdi', label: 'নরসিংদী' },
    { value: 'rajbari', label: 'রাজবাড়ী' },
    { value: 'shariatpur', label: 'শরীয়তপুর' },
    { value: 'tangail', label: 'টাঙ্গাইল' },
  ],
  chittagong: [
    { value: 'bandarban', label: 'বান্দরবান' },
    { value: 'brahmanbaria', label: 'ব্রাহ্মণবাড়িয়া' },
    { value: 'chandpur', label: 'চাঁদপুর' },
    { value: 'chittagong', label: 'চট্টগ্রাম' },
    { value: 'comilla', label: 'কুমিল্লা' },
    { value: 'coxsbazar', label: "কক্সবাজার" },
    { value: 'feni', label: 'ফেনী' },
    { value: 'khagrachhari', label: 'খাগড়াছড়ি' },
    { value: 'lakshmipur', label: 'লক্ষ্মীপুর' },
    { value: 'noakhali', label: 'নোয়াখালী' },
    { value: 'rangamati', label: 'রাঙ্গামাটি' },
  ],
  rajshahi: [
    { value: 'bogra', label: 'বগুড়া' },
    { value: 'joypurhat', label: 'জয়পুরহাট' },
    { value: 'naogaon', label: 'নওগাঁ' },
    { value: 'natore', label: 'নাটোর' },
    { value: 'chapainawabganj', label: 'চাঁপাইনবাবগঞ্জ' },
    { value: 'pabna', label: 'পাবনা' },
    { value: 'rajshahi', label: 'রাজশাহী' },
    { value: 'sirajganj', label: 'সিরাজগঞ্জ' },
  ],
  khulna: [
    { value: 'bagerhat', label: 'বাগেরহাট' },
    { value: 'chuadanga', label: 'চুয়াডাঙ্গা' },
    { value: 'jessore', label: 'যশোর' },
    { value: 'jhenaidah', label: 'ঝিনাইদহ' },
    { value: 'khulna', label: 'খুলনা' },
    { value: 'kushtia', label: 'কুষ্টিয়া' },
    { value: 'magura', label: 'মাগুরা' },
    { value: 'meherpur', label: 'মেহেরপুর' },
    { value: 'narail', label: 'নড়াইল' },
    { value: 'satkhira', label: 'সাতক্ষীরা' },
  ],
  barisal: [
    { value: 'barguna', label: 'বরগুনা' },
    { value: 'barisal', label: 'বরিশাল' },
    { value: 'bhola', label: 'ভোলা' },
    { value: 'jhalokati', label: 'ঝালকাঠি' },
    { value: 'patuakhali', label: 'পটুয়াখালী' },
    { value: 'pirojpur', label: 'পিরোজপুর' },
  ],
  sylhet: [
    { value: 'habiganj', label: 'হবিগঞ্জ' },
    { value: 'moulvibazar', label: 'মৌলভীবাজার' },
    { value: 'sunamganj', label: 'সুনামগঞ্জ' },
    { value: 'sylhet', label: 'সিলেট' },
  ],
  rangpur: [
    { value: 'dinajpur', label: 'দিনাজপুর' },
    { value: 'gaibandha', label: 'গাইবান্ধা' },
    { value: 'kurigram', label: 'কুড়িগ্রাম' },
    { value: 'lalmonirhat', label: 'লালমনিরহাট' },
    { value: 'nilphamari', label: 'নীলফামারী' },
    { value: 'panchagarh', label: 'পঞ্চগড়' },
    { value: 'rangpur', label: 'রংপুর' },
    { value: 'thakurgaon', label: 'ঠাকুরগাঁও' },
  ],
  mymensingh: [
    { value: 'jamalpur', label: 'জামালপুর' },
    { value: 'mymensingh', label: 'ময়মনসিংহ' },
    { value: 'netrokona', label: 'নেত্রকোণা' },
    { value: 'sherpur', label: 'শেরপুর' },
  ],
};
